[project]
name = "minimal-transformer-llm"
version = "0.1.0"
description = "Lightweight implementation of transformer architecture for large language models."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
